### ISSUE TITLE
Using ADXL sensor instead of BME280 Sensor

### ISSUE THREAD

**Issue by DrFirstLee** [abish7643/ESP32Cam-I2CSensors#1]
Hello '
I am student from Seoul, South Korea and ESP32 starter.
Nowadays I am really enjoying ADRUINO and got many helps from many GURU.

I am trying to connect motion sensor to esp32-cam and I found your amazing materials.
It is really helpful.  Unfortunately I am using ADXL-345 so there is little difference.
Which is i am using #include <Adafruit_ADXL345_U.h> while yours is #include <Adafruit_BME280.h>.
because of this difference I can't  Initalize the Sensor correctly.

![question](https://user-images.githubusercontent.com/43365171/132658234-69b3a074-c33c-41f1-9723-d14fa81af539.JPG)

can you tell me the way to solve this problem??

Thanks in advance

SIncerely

**Comment by abish7643** [comment]
I don't have any accelerometer lying around, but I checked the library. 

There's no such functions like the one you showed (the line with error). If you didn't understand that, you passed two attributes, one is the address. The library don't have a function with a second attribute. So this isn't the approach.
