### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by felipebraz** [abish7643/ESP32Cam-I2CSensors#2]
Hi, I´m in a learning phase so sometimes simples things appears to be impossile to me, and one of it is: is this library can be used with ADS1115?
The main goal is to connect a rain sensor on ESP32-CAM, as I can´t use analog ports when WiFi is being used this is my (maybe) only option. Is it possible? Is there any example?

**Comment by abish7643** [comment]
This isn't a library, just an example of how you could overcome the issue. 
You could read my [post](https://3iinc.xyz/blog/how-to-use-i2c-sensor-bme280-with-esp32cam/) for understanding the issue in detail. 

In short, ESP32 has two I2C Bus, one is used by the camera. So the other one can be initiated explicitly with the pins of your choice (Better Avoid Strapping Pins). So use the **TwoWire** library (Built-in) to initiate the second bus. And use that bus to configure your ADS1115. This example shows BMP280, you can remove that and use the ADS1115 library.
